# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic.bd
# Block Designs: The module: 'pfm_dynamic' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_gpio_null_0 || ORIG_REF_NAME==pfm_dynamic_axi_gpio_null_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_interconnect_0_0/pfm_dynamic_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_interconnect_0_0 || ORIG_REF_NAME==pfm_dynamic_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_interconnect_1_0/pfm_dynamic_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_interconnect_1_0 || ORIG_REF_NAME==pfm_dynamic_axi_interconnect_1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_interconnect_hpm0fpd_0/pfm_dynamic_axi_interconnect_hpm0fpd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_interconnect_hpm0fpd_0 || ORIG_REF_NAME==pfm_dynamic_axi_interconnect_hpm0fpd_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_2_0/pfm_dynamic_axi_mmu_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_2_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_2_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_3_0/pfm_dynamic_axi_mmu_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_3_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_3_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_4_0/pfm_dynamic_axi_mmu_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_4_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_4_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_5_0/pfm_dynamic_axi_mmu_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_5_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_5_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_register_slice_hpm0fpd_0/pfm_dynamic_axi_register_slice_hpm0fpd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_register_slice_hpm0fpd_0 || ORIG_REF_NAME==pfm_dynamic_axi_register_slice_hpm0fpd_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_0_0/pfm_dynamic_axi_vip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_0_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_0_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_2_0/pfm_dynamic_axi_vip_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_2_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_2_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_3_0/pfm_dynamic_axi_vip_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_3_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_3_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_4_0/pfm_dynamic_axi_vip_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_4_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_4_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_5_0/pfm_dynamic_axi_vip_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_5_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_5_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_ctrl_userpf_0/pfm_dynamic_axi_vip_ctrl_userpf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_ctrl_userpf_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_ctrl_userpf_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_hpm0fpd_0/pfm_dynamic_axi_vip_hpm0fpd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_hpm0fpd_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_hpm0fpd_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_debug_bridge_xsdbm_0 || ORIG_REF_NAME==pfm_dynamic_debug_bridge_xsdbm_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_interconnect_axifull_1_user_slr1_0/pfm_dynamic_interconnect_axifull_1_user_slr1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_interconnect_axifull_1_user_slr1_0 || ORIG_REF_NAME==pfm_dynamic_interconnect_axifull_1_user_slr1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_interconnect_axifull_2_user_slr1_0/pfm_dynamic_interconnect_axifull_2_user_slr1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_interconnect_axifull_2_user_slr1_0 || ORIG_REF_NAME==pfm_dynamic_interconnect_axifull_2_user_slr1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_interconnect_axilite_user_slr1_0/pfm_dynamic_interconnect_axilite_user_slr1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_interconnect_axilite_user_slr1_0 || ORIG_REF_NAME==pfm_dynamic_interconnect_axilite_user_slr1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_xlconcat_interrupt_0_0/pfm_dynamic_xlconcat_interrupt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_xlconcat_interrupt_0_0 || ORIG_REF_NAME==pfm_dynamic_xlconcat_interrupt_0_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_control_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_control_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel2_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel2_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel3_0/pfm_dynamic_psreset_gate_pr_kernel3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel3_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel3_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel4_0/pfm_dynamic_psreset_gate_pr_kernel4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel4_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel4_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel5_0/pfm_dynamic_psreset_gate_pr_kernel5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel5_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel5_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel6_0/pfm_dynamic_psreset_gate_pr_kernel6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel6_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel6_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_18/pfm_dynamic_s00_regslice_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_18 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_18} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_19 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_19} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_20/pfm_dynamic_s00_regslice_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_20 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_20} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_21/pfm_dynamic_s00_regslice_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_21 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_21} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_22/pfm_dynamic_s00_regslice_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_22 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_22} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_23/pfm_dynamic_s00_regslice_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_23 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_23} -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic.bd
# Block Designs: The module: 'pfm_dynamic' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_gpio_null_0 || ORIG_REF_NAME==pfm_dynamic_axi_gpio_null_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_interconnect_0_0/pfm_dynamic_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_interconnect_0_0 || ORIG_REF_NAME==pfm_dynamic_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_interconnect_1_0/pfm_dynamic_axi_interconnect_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_interconnect_1_0 || ORIG_REF_NAME==pfm_dynamic_axi_interconnect_1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_interconnect_hpm0fpd_0/pfm_dynamic_axi_interconnect_hpm0fpd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_interconnect_hpm0fpd_0 || ORIG_REF_NAME==pfm_dynamic_axi_interconnect_hpm0fpd_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_2_0/pfm_dynamic_axi_mmu_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_2_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_2_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_3_0/pfm_dynamic_axi_mmu_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_3_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_3_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_4_0/pfm_dynamic_axi_mmu_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_4_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_4_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_5_0/pfm_dynamic_axi_mmu_5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_mmu_5_0 || ORIG_REF_NAME==pfm_dynamic_axi_mmu_5_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_register_slice_hpm0fpd_0/pfm_dynamic_axi_register_slice_hpm0fpd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_register_slice_hpm0fpd_0 || ORIG_REF_NAME==pfm_dynamic_axi_register_slice_hpm0fpd_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_0_0/pfm_dynamic_axi_vip_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_0_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_0_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_2_0/pfm_dynamic_axi_vip_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_2_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_2_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_3_0/pfm_dynamic_axi_vip_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_3_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_3_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_4_0/pfm_dynamic_axi_vip_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_4_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_4_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_5_0/pfm_dynamic_axi_vip_5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_5_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_5_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_ctrl_userpf_0/pfm_dynamic_axi_vip_ctrl_userpf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_ctrl_userpf_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_ctrl_userpf_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_hpm0fpd_0/pfm_dynamic_axi_vip_hpm0fpd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_axi_vip_hpm0fpd_0 || ORIG_REF_NAME==pfm_dynamic_axi_vip_hpm0fpd_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_debug_bridge_xsdbm_0 || ORIG_REF_NAME==pfm_dynamic_debug_bridge_xsdbm_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_interconnect_axifull_1_user_slr1_0/pfm_dynamic_interconnect_axifull_1_user_slr1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_interconnect_axifull_1_user_slr1_0 || ORIG_REF_NAME==pfm_dynamic_interconnect_axifull_1_user_slr1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_interconnect_axifull_2_user_slr1_0/pfm_dynamic_interconnect_axifull_2_user_slr1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_interconnect_axifull_2_user_slr1_0 || ORIG_REF_NAME==pfm_dynamic_interconnect_axifull_2_user_slr1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_interconnect_axilite_user_slr1_0/pfm_dynamic_interconnect_axilite_user_slr1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_interconnect_axilite_user_slr1_0 || ORIG_REF_NAME==pfm_dynamic_interconnect_axilite_user_slr1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_xlconcat_interrupt_0_0/pfm_dynamic_xlconcat_interrupt_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_xlconcat_interrupt_0_0 || ORIG_REF_NAME==pfm_dynamic_xlconcat_interrupt_0_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_control_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_control_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel2_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel2_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel3_0/pfm_dynamic_psreset_gate_pr_kernel3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel3_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel3_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel4_0/pfm_dynamic_psreset_gate_pr_kernel4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel4_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel4_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel5_0/pfm_dynamic_psreset_gate_pr_kernel5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel5_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel5_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel6_0/pfm_dynamic_psreset_gate_pr_kernel6_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_psreset_gate_pr_kernel6_0 || ORIG_REF_NAME==pfm_dynamic_psreset_gate_pr_kernel6_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_18/pfm_dynamic_s00_regslice_18.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_18 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_18} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_19 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_19} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_20/pfm_dynamic_s00_regslice_20.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_20 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_20} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_21/pfm_dynamic_s00_regslice_21.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_21 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_21} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_22/pfm_dynamic_s00_regslice_22.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_22 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_22} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_23/pfm_dynamic_s00_regslice_23.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_dynamic_s00_regslice_23 || ORIG_REF_NAME==pfm_dynamic_s00_regslice_23} -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic'. Do not add the DONT_TOUCH constraint.
