# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.runs/bd_pfm_dynamic_synth_1/pfm_dynamic.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "bd_pfm_dynamic_synth_1" START { ROLLUP_AUTO }
set_param project.enablePRFlowIPI 1
set_param platform.populateFeatureRomInWriteHwPlatform 0
set_param ips.enableSLRParameter 2
set_param checkpoint.useBaseFileNamesWhileWritingDCP 1
set_param bd.skipSupportedIPCheck 1
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.cache/wt [current_project]
set_property parent.project_path /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_repo_paths /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/sources/iprepo [current_project]
update_ip_catalog
set_property ip_output_repo /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic.bd
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_2_0/pfm_dynamic_axi_mmu_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_3_0/pfm_dynamic_axi_mmu_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_4_0/pfm_dynamic_axi_mmu_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_mmu_5_0/pfm_dynamic_axi_mmu_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_register_slice_hpm0fpd_0/pfm_dynamic_axi_register_slice_hpm0fpd_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_register_slice_hpm0fpd_0/pfm_dynamic_axi_register_slice_hpm0fpd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_0_0/pfm_dynamic_axi_vip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_2_0/pfm_dynamic_axi_vip_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_3_0/pfm_dynamic_axi_vip_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_4_0/pfm_dynamic_axi_vip_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_5_0/pfm_dynamic_axi_vip_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_ctrl_userpf_0/pfm_dynamic_axi_vip_ctrl_userpf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_axi_vip_hpm0fpd_0/pfm_dynamic_axi_vip_hpm0fpd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/bd_ebbe_xsdbm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/bd_ebbe_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel3_0/pfm_dynamic_psreset_gate_pr_kernel3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel3_0/pfm_dynamic_psreset_gate_pr_kernel3_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel3_0/pfm_dynamic_psreset_gate_pr_kernel3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel4_0/pfm_dynamic_psreset_gate_pr_kernel4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel4_0/pfm_dynamic_psreset_gate_pr_kernel4_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel4_0/pfm_dynamic_psreset_gate_pr_kernel4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel5_0/pfm_dynamic_psreset_gate_pr_kernel5_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel5_0/pfm_dynamic_psreset_gate_pr_kernel5_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel5_0/pfm_dynamic_psreset_gate_pr_kernel5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel6_0/pfm_dynamic_psreset_gate_pr_kernel6_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel6_0/pfm_dynamic_psreset_gate_pr_kernel6_0.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_psreset_gate_pr_kernel6_0/pfm_dynamic_psreset_gate_pr_kernel6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_18/pfm_dynamic_s00_regslice_18_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_18/pfm_dynamic_s00_regslice_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_20/pfm_dynamic_s00_regslice_20_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_20/pfm_dynamic_s00_regslice_20_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_21/pfm_dynamic_s00_regslice_21_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_21/pfm_dynamic_s00_regslice_21_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_22/pfm_dynamic_s00_regslice_22_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_22/pfm_dynamic_s00_regslice_22_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_23/pfm_dynamic_s00_regslice_23_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_23/pfm_dynamic_s00_regslice_23_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top pfm_dynamic -part xczu9eg-ffvb1156-2-e -mode out_of_context
OPTRACE "synth_design" END { }

rename_ref -prefix_all pfm_dynamic_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pfm_dynamic.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "bd_pfm_dynamic_synth_1_synth_report_utilization_0" "report_utilization -file pfm_dynamic_utilization_synth.rpt -pb pfm_dynamic_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.runs/bd_pfm_dynamic_synth_1/pfm_dynamic.dcp /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.ip_user_files/bd/pfm_dynamic]} {
  catch { 
    file copy -force /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_stub.v /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.ip_user_files/bd/pfm_dynamic
  }
}

if {[file isdir /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.ip_user_files/bd/pfm_dynamic]} {
  catch { 
    file copy -force /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/pfm_dynamic_stub.vhdl /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.ip_user_files/bd/pfm_dynamic
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "bd_pfm_dynamic_synth_1" END { }
