# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/pfm_top_debug_bridge_xvc_0.xci
# IP: The module: 'pfm_top_debug_bridge_xvc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/bd_204d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d || ORIG_REF_NAME==bd_204d} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_0/bd_204d_axi_jtag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_axi_jtag_0 || ORIG_REF_NAME==bd_204d_axi_jtag_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_1/bd_204d_bsip_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bsip_0 || ORIG_REF_NAME==bd_204d_bsip_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_2/bd_204d_bs_switch_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bs_switch_1_0 || ORIG_REF_NAME==bd_204d_bs_switch_1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_3/bd_204d_bs_switch_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bs_switch_2 || ORIG_REF_NAME==bd_204d_bs_switch_2} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_4/bd_204d_bs_mux_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bs_mux_0 || ORIG_REF_NAME==bd_204d_bs_mux_0} -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/bd_204d_ooc.xdc

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/pfm_top_debug_bridge_xvc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_top_debug_bridge_xvc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/pfm_top_debug_bridge_xvc_0.xci
# IP: The module: 'pfm_top_debug_bridge_xvc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/bd_204d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d || ORIG_REF_NAME==bd_204d} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_0/bd_204d_axi_jtag_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_axi_jtag_0 || ORIG_REF_NAME==bd_204d_axi_jtag_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_1/bd_204d_bsip_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bsip_0 || ORIG_REF_NAME==bd_204d_bsip_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_2/bd_204d_bs_switch_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bs_switch_1_0 || ORIG_REF_NAME==bd_204d_bs_switch_1_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_3/bd_204d_bs_switch_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bs_switch_2 || ORIG_REF_NAME==bd_204d_bs_switch_2} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_4/bd_204d_bs_mux_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_204d_bs_mux_0 || ORIG_REF_NAME==bd_204d_bs_mux_0} -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/bd_204d_ooc.xdc

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/pfm_top_debug_bridge_xvc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_top_debug_bridge_xvc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
