# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/static_impl_early.xdc

# XDC: imports/constraints/dynamic_impl.xdc

# Block Designs: bd/pfm_top/pfm_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top || ORIG_REF_NAME==pfm_top} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_intc_0_0/pfm_top_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_intc_0_0 || ORIG_REF_NAME==pfm_top_axi_intc_0_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_xbar_0/pfm_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_xbar_0 || ORIG_REF_NAME==pfm_top_xbar_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_interconnect_0_0/pfm_top_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_interconnect_0_0 || ORIG_REF_NAME==pfm_top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_interconnect_mgmt_0/pfm_top_axi_interconnect_mgmt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_interconnect_mgmt_0 || ORIG_REF_NAME==pfm_top_axi_interconnect_mgmt_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_xbar_1/pfm_top_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_xbar_1 || ORIG_REF_NAME==pfm_top_xbar_1} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_interconnect_user_0/pfm_top_axi_interconnect_user_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_interconnect_user_0 || ORIG_REF_NAME==pfm_top_axi_interconnect_user_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_vip_0_0/pfm_top_axi_vip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_vip_0_0 || ORIG_REF_NAME==pfm_top_axi_vip_0_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_vip_1_0/pfm_top_axi_vip_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_vip_1_0 || ORIG_REF_NAME==pfm_top_axi_vip_1_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_vip_2_0/pfm_top_axi_vip_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_vip_2_0 || ORIG_REF_NAME==pfm_top_axi_vip_2_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_vip_data_m00_axi_1_0/pfm_top_axi_vip_data_m00_axi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_vip_data_m00_axi_1_0 || ORIG_REF_NAME==pfm_top_axi_vip_data_m00_axi_1_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_clkwiz_sysclks_0/pfm_top_clkwiz_sysclks_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_clkwiz_sysclks_0 || ORIG_REF_NAME==pfm_top_clkwiz_sysclks_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_psreset_ctrlclk_0/pfm_top_psreset_ctrlclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_psreset_ctrlclk_0 || ORIG_REF_NAME==pfm_top_psreset_ctrlclk_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/pfm_top_debug_bridge_xvc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_debug_bridge_xvc_0 || ORIG_REF_NAME==pfm_top_debug_bridge_xvc_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_register_slice_0_0/pfm_top_axi_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_register_slice_0_0 || ORIG_REF_NAME==pfm_top_axi_register_slice_0_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_axi_register_slice_1_0/pfm_top_axi_register_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_axi_register_slice_1_0 || ORIG_REF_NAME==pfm_top_axi_register_slice_1_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_gate_pr_0/pfm_top_gate_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_gate_pr_0 || ORIG_REF_NAME==pfm_top_gate_pr_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_psreset_regslice_ctrl_pr_0/pfm_top_psreset_regslice_ctrl_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_psreset_regslice_ctrl_pr_0 || ORIG_REF_NAME==pfm_top_psreset_regslice_ctrl_pr_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_psreset_regslice_data_pr_0/pfm_top_psreset_regslice_data_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_psreset_regslice_data_pr_0 || ORIG_REF_NAME==pfm_top_psreset_regslice_data_pr_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_regslice_control_userpf_0/pfm_top_regslice_control_userpf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_regslice_control_userpf_0 || ORIG_REF_NAME==pfm_top_regslice_control_userpf_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_regslice_data_periph_1_0/pfm_top_regslice_data_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_regslice_data_periph_1_0 || ORIG_REF_NAME==pfm_top_regslice_data_periph_1_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_regslice_ddrmem_2_0/pfm_top_regslice_ddrmem_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_regslice_ddrmem_2_0 || ORIG_REF_NAME==pfm_top_regslice_ddrmem_2_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_regslice_ddrmem_3_0/pfm_top_regslice_ddrmem_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_regslice_ddrmem_3_0 || ORIG_REF_NAME==pfm_top_regslice_ddrmem_3_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_slice_reset_kernel_pr_0/pfm_top_slice_reset_kernel_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_slice_reset_kernel_pr_0 || ORIG_REF_NAME==pfm_top_slice_reset_kernel_pr_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_slice_reset_system_pr_0/pfm_top_slice_reset_system_pr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_slice_reset_system_pr_0 || ORIG_REF_NAME==pfm_top_slice_reset_system_pr_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_xlconcat_0_0/pfm_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_xlconcat_0_0 || ORIG_REF_NAME==pfm_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_zynq_ultra_ps_e_0_0/pfm_top_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==pfm_top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/pfm_top/ip/pfm_top_auto_pc_0/pfm_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pfm_top_auto_pc_0 || ORIG_REF_NAME==pfm_top_auto_pc_0} -quiet] -quiet

# XDC: bd/pfm_top/pfm_top_ooc.xdc
