# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19.xci
# IP: The module: 'pfm_dynamic_s00_regslice_19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_s00_regslice_19'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_s00_regslice_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19.xci
# IP: The module: 'pfm_dynamic_s00_regslice_19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_s00_regslice_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_s00_regslice_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
