# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_3/constraints/bs_switch.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_204d_bs_switch_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_3/bd_204d_bs_switch_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_204d_bs_switch_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_3/constraints/bs_switch.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_204d_bs_switch_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_top/ip/pfm_top_debug_bridge_xvc_0/bd_0/ip/ip_3/bd_204d_bs_switch_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_204d_bs_switch_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
