# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0.xci
# IP: The module: 'pfm_dynamic_debug_bridge_xsdbm_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/bd_ebbe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ebbe || ORIG_REF_NAME==bd_ebbe} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/bd_ebbe_xsdbm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ebbe_xsdbm_0 || ORIG_REF_NAME==bd_ebbe_xsdbm_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_1/bd_ebbe_lut_buffer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ebbe_lut_buffer_0 || ORIG_REF_NAME==bd_ebbe_lut_buffer_0} -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/bd_ebbe_ooc.xdc

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_debug_bridge_xsdbm_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0.xci
# IP: The module: 'pfm_dynamic_debug_bridge_xsdbm_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/bd_ebbe.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ebbe || ORIG_REF_NAME==bd_ebbe} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/bd_ebbe_xsdbm_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ebbe_xsdbm_0 || ORIG_REF_NAME==bd_ebbe_xsdbm_0} -quiet] -quiet

# IP: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_1/bd_ebbe_lut_buffer_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ebbe_lut_buffer_0 || ORIG_REF_NAME==bd_ebbe_lut_buffer_0} -quiet] -quiet

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/bd_ebbe_ooc.xdc

# XDC: /home/endrix/git/streamblocks/Vitis_Embedded_Platform_Source/Xilinx_Official_Platforms/zcu102_base_dfx/vivado/xilinx_zcu102_dynamic_0_1/xilinx_zcu102_dynamic_0_1.srcs/sources_1/bd/pfm_dynamic/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_debug_bridge_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
